#!/bin/sh

set -ex

if [ "$1" = "" ]; then
    echo "usage: $0 <loggregator-ca.crt> <loggregator-ca.key>"
    echo "       $0 no-loggregator-ca"
    exit 1
fi

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="statsd-injector-certs"
mkdir -p ${depot_path}

if [ "$1" = "no-loggregator-ca" ]; then
    # CA to sign statsdinjector certs
    certstrap --depot-path ${depot_path} init --passphrase '' --common-name loggregatorCA
    mv -f ${depot_path}/loggregatorCA.crt ${depot_path}/loggregator-ca.crt
    mv -f ${depot_path}/loggregatorCA.key ${depot_path}/loggregator-ca.key
    mv -f ${depot_path}/loggregatorCA.crl ${depot_path}/loggregator-ca.crl
    loggregator_ca_name=loggregator-ca
else
    loggregator_ca_cert_path=$1
    loggregator_ca_key_path=$2
    loggregator_ca_name=$(basename ${loggregator_ca_cert_path} ".crt")
    ln -s ${loggregator_ca_cert_path} ${depot_path}/
    ln -s ${loggregator_ca_key_path} ${depot_path}/
fi

# Statsd injector certificate
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name statsdinjector
certstrap --depot-path ${depot_path} sign statsdinjector --CA ${loggregator_ca_name}
